name: Tests
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  action:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: antrea-io/has-changes@v2
      id: check_diff
    outputs:
      has_changes: ${{ steps.run_action.outputs.has_changes }}
